# Generated by Django 4.2.30 on 2026-08-03 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='id_blog',
            new_name='blog',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='id_user',
            new_name='user',
        ),
    ]
