# Generated by Django 4.2.30 on 2026-08-10 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='commentInBlog',
        ),
    ]
