# Generated by Django 4.2.30 on 2026-08-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.TextField(blank=True, choices=[('sale', 'Sale'), ('normal', 'Normal')], max_length=20, null=True),
        ),
    ]
