# Generated by Django 4.2.30 on 2026-08-20 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
