# Generated by Django 4.2.30 on 2026-07-28 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercustomer',
            name='confirm_password',
        ),
    ]
