# Generated by Django 4.2.30 on 2026-09-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_usercustomer_confirm_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustomer',
            name='phone',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
